
% CONVEX.RULE_PRINT(text,present)
% print all the boards representing a rule and its key

%% warnings

%% function
function rule_print(obj,text,keys,rule)
    obj.board_print({   [text,' keys'], ...
                        [text,' zero'], ...
                        [text,' same'], ...
                        [text,' diff'], ...
                        [text,' ones']},...
                    {   keys,      ...
                        rule(:,1), ...
                        rule(:,2), ...
                        rule(:,3), ...
                        rule(:,4)  });
end